@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueLocationList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueLocationList
UniqueTagList -[hidden]down- UniqueLocationList

UniqueTagList -right-> "*" Tag
UniqueLocationList -right-> Location

Location -up-> "*" Tag

Location *--> Name
Location *--> Phone
Location *--> Email
Location *--> Address
@enduml
